name: 'cv2.fun everyday'
on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  cv2-fun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./packages/cv2-fun-sign-in
        with:
          emails: ${{ secrets.CV2_FUN_EMAILS }}
          passwords: ${{ secrets.CV2_FUN_PASSWORDS }}
